// Code generated by Slice Machine. DO NOT EDIT.

import About from './About';
import Achivements from './Achivements';
import Blogs from './Blogs';
import Contact from './Contact';
import Faq from './Faq';
import Features from './Features';
import Footer from './Footer';
import Header from './Header';
import Testimonials from './Testimonials';
import Welcome from './Welcome';

export {
	About,
	Achivements,
	Blogs,
	Contact,
	Faq,
	Features,
	Footer,
	Header,
	Testimonials,
	Welcome,
};

export const components = {
	about: About,
	achivements: Achivements,
	blogs: Blogs,
	contact: Contact,
	faq: Faq,
	features: Features,
	footer: Footer,
	header: Header,
	testimonials: Testimonials,
	welcome: Welcome,
};
